spring.application.name=Quipux


spring.datasource.url=jdbc:h2:mem:peopledb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.security.username=admin
app.security.password=admin123

nationalize.base-url=https://api.nationalize.io
nationalize.api-key=${NATIONALIZE_API_KEY:}